---
# tasks file for upgrade (Debian)

- name: Install aptitude (Debian)
  ansible.builtin.apt:
    name: aptitude
    force_apt_get: yes
    update_cache: yes
- name: Upgrade all packages (Debian)
  ansible.builtin.apt:
    upgrade: full
