---
# tasks file for upgrade
- name: Install aptitude
  apt:
    name: 'aptitude'
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: reinstall cryptsetup-initramfs to fix upgrade
  shell: apt-get update
  when: ansible_distribution_release == "kali-rolling"
  
- name: reinstall cryptsetup-initramfs to fix upgrade
  shell: apt-get install --reinstall cryptsetup-initramfs
  when: ansible_distribution_release == "kali-rolling"

- name: reinstall cryptsetup-initramfs to fix upgrade
  shell: DEBIAN_FRONTEND=noninteractive apt-get -yy upgrade
  when: ansible_distribution_release == "kali-rolling"

- name: Upgrade all Kali packages
  apt:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Upgrade all Debian packages
  apt:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "Debian" and ansible_distribution_release != "kali-rolling"

- name: Upgrade all RedHat packages
  yum:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "RedHat"
