---
# tasks file for upgrade
- name: Install aptitude
  apt:
    name: 'aptitude'
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all Debian packages
  apt:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: >
    ansible_os_family == "Debian" and
    ansible_distribution_release != "kali-rolling"

- name: Reinstall cryptsetup-initramfs so upgrade doesn't fail
  apt:
    name: 'cryptsetup-initramfs'
    update_cache: yes
  when: ansible_distribution_release == "kali-rolling"

- name: apt-get update
  command: apt-get update
  args:
    warn: false
  when: ansible_distribution_release == "kali-rolling"
  # ignore idempotence test because apt-get update cannot guarantee
  # idempotence compliance
  tags: molecule-idempotence-notest

# Upgrading with command module instead of apt ansible module
# See https://github.com/ansible/ansible/issues/63134 for more info
- name: Upgrade with noninteractive frontend to handle GUI prompts
  command: apt-get -yy upgrade
  when: ansible_distribution_release == "kali-rolling"
  args:
    warn: false
  environment:
    DEBIAN_FRONTEND: noninteractive
  # ignore idempotence test because apt-get upgrade cannot guarantee
  # idempotence compliance
  tags: molecule-idempotence-notest

- name: Upgrade all RedHat packages
  yum:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "RedHat"
