---
# tasks file for upgrade

- name: Load tasks file with install tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        # The OS family and distribution for Kali is "Kali GNU/Linux",
        # which is not an allowable file name in Linux due to the
        # slash.  We will allow Kali to fall through and use the
        # Debian tasks file.
        - Debian.yml
      paths:
        - "{{ role_path }}/tasks"
