---
# tasks file for upgrade

- name: Debian-specific tasks
  block:
    - name: Install aptitude
      apt:
        name: 'aptitude'
        force_apt_get: yes
    - name: Upgrade all packages (Debian)
      apt:
        name: '*'
        # ansible-lint generates a warning that "package installs
        # should not use latest" here, but this is one place where we
        # want to use it.
        state: latest  # noqa 403
        update_cache: yes
  when: ansible_os_family == "Debian" or ansible_os_family == "Kali GNU/Linux"

- name: Upgrade all packages (RedHat)
  yum:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "RedHat"
