---
- name: Load tasks file with install tasks based on the detected package manager
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_pkg_mgr }}.yml"
      paths:
        - "{{ role_path }}/tasks"
