---
- name: Load tasks file with install tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/tasks"

# On Debian 10, the 4.19.132-1 kernel is randomly locking up on us,
# while the 4.19.118-2 kernel worked just fine.  By turning on kdump
# functionality, we were able to verify that the cause of the lockups
# is exactly what is discussed in these links: *
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966846 *
# https://lkml.org/lkml/2020/7/20/883
#
# Until we can verify that the kernel bug has been fixed, we will
# install the 4.19.118-2 kernel and reconfigure grub to set it as the
# default kernel.
#
# Note that this is done _only_ for version 10 of the Debian
# distribution and not for other distributions in the Debian family.
- name: Hold kernel for Debian distribution
  include: Debian_10_hold_kernel.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version == "10"
