---
# tasks file for upgrade
- name: Install aptitude
  apt:
    name: 'aptitude'
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all Debian packages
  apt:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: >
    ansible_os_family == "Debian" and
    ansible_distribution_release != "kali-rolling"

- name: Reinstall cryptsetup-initramfs so upgrade doesn't fail
  apt:
    name: 'cryptsetup-initramfs'
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_distribution_release == "kali-rolling"

- name: Upgrade Kali packages/get around GUI prompts with environment variable
  apt:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_distribution_release == "kali-rolling"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Upgrade all RedHat packages
  yum:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
  when: ansible_os_family == "RedHat"
