---
# tasks file for upgrade (RedHat)

- name: Upgrade all packages (RedHat)
  yum:
    name: '*'
    # ansible-lint generates a warning that "package installs should
    # not use latest" here, but this is one place where we want to use
    # it.
    state: latest  # noqa 403
    update_cache: yes
