---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazonlinux2
    image: amazonlinux:2
    groups:
      - redhat
  - name: debian9
    image: debian:stretch-slim
    groups:
      - debian
  - name: debian10
    image: debian:buster-slim
    groups:
      - debian
  - name: fedora29
    image: fedora:29
    groups:
      - redhat
  # Ansible currently insists on installing python2-dnf, which does
  # not exist in Fedora 30.  Until that is resolved, we can't use
  # Fedora 30.
  # - name: fedora30
  #   image: fedora:30
  - name: fedora31
    image: fedora:31
    groups:
      - redhat
  - name: kali
    image: kalilinux/kali-rolling
    groups:
      - debian
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
