---
# On Debian 10, the 4.19.132-1 kernel is randomly locking up on us,
# while the 4.19.118-2 kernel worked just fine.  Until we can
# determine the exact reason for the failure and verify that it has
# been fixed, we will install the 4.19.118-2 kernel and hold that
# package.
#
# To make a better test platform, we go ahead and install the latest
# kernel for Debian 10.  The base image we use to build our AWS AMIs
# already has a kernel installed, so this will allow us to confirm
# that it gets removed in our molecule tests.
- name: Group hosts by OS distribution
  hosts: all
  tasks:
    - name: Group hosts by OS distribution
      ansible.builtin.group_by:
        key: os_{{ ansible_distribution }}_{{ ansible_distribution_release }}
- name: Install the latest kernel (Debian 10)
  hosts: os_Debian_buster
  tasks:
    - name: Install aptitude (Debian 10)
      ansible.builtin.apt:
        name: aptitude
        force_apt_get: yes
        update_cache: yes
    - name: Install the latest kernel (Debian 10)
      ansible.builtin.apt:
        name:
          - linux-headers-cloud-amd64
          - linux-image-cloud-amd64
